fullnameOverride: ""
nameOverride: ""

deployment:
  replicas: 2
  containers:
    - name: whoami
      image: containous/whoami
      pullPolicy: Always
      tag: latest
      namePort: http
      port: 80
    - name: metrics-sidecar
      image: nginx/nginx-prometheus-exporter
      pullPolicy: Always
      tag: 1.3.0
      port: 9112
      namePort: metrics
      scrapeUri: "http://127.0.0.1:80/"

# metricsSidecar:
#   enabled: true
#   image:
#     repository: nginx/nginx-prometheus-exporter
#     tag: "1.3.0"
#   port: 9112
#   scrapeUri: "http://127.0.0.1:80/"

service:
  type: ClusterIP
  port: 80
  metricsPort: 9112
  targetPort: 8080

ingress:
  enabled: true
  ClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  hosts:
    - host: whoami.local
      paths:
        - path: /
          pathType: Prefix
          port: 80
  tls:
    enabled: true
    secretName: whoami-tls

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

monitoring:
  enabled: true
  interval: 15s
  release: kube-prom-stack

labels:
  environment: production

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 5 # tempo em segundos para observar antes de aumentar
      selectPolicy: Max # pode ser Max, Min ou Disabled
      policies:
        - type: Percent
          value: 100 # Pode ser Percent ou Pods. É o Percentual ou número de pods aumentar de uma vez
          periodSeconds: 60 # período em segundos para aplicar a política
        - type: Pods
          value: 4 # Pode ser Percent ou Pods. É o Percentual ou número de pods aumentar de uma vez
          periodSeconds: 60 # período em segundos para aplicar a política
    scaleDown:
      stabilizationWindowSeconds: 300
      selectPolicy: Min
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
        - type: Pods
          value: 4
          periodSeconds: 15