fullnameOverride: ""
nameOverride: ""

deployment:
  replicas: 2
  containers:
    - name: whoami
      image: containous/whoami
      pullPolicy: Always
      tag: latest
      namePort: web
      port: 80
    - name: metrics-sidecar
      image: nginx/nginx-prometheus-exporter
      pullPolicy: Always
      tag: 1.3.0
      port: 9112
      namePort: metrics
      scrapeUri: "http://127.0.0.1:80/"
    - name: stress
      image: polinux/stress
      command: ["/bin/sh", "-c"]
      args:
        - stress --cpu 2 --vm 1 --vm-bytes 128M --timeout 300s


service:
  type: ClusterIP
  ports:
    - name: web
      port: 80
      targetPort: 80
    - name: metrics
      port: 9112
      targetPort: 9112

ingress:
  enabled: false
  ClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-local
  hosts:
    - host: whoami.local
      paths:
        - path: /
          pathType: Prefix
          port: 80
  tls:
    enabled: false
    secretName: whoami-tls

resources:
  requests:
    cpu: 100m   # HPA vai usar isso como base
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 30
  targetMemoryUtilizationPercentage: 30
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      selectPolicy: Max
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
        - type: Pods
          value: 2
          periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 60
      selectPolicy: Min
      policies:
        - type: Percent
          value: 50
          periodSeconds: 30