{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "whoami.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "whoami.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.ClassName }}
  ingressClassName: {{ .Values.ingress.ClassName }}
  {{- end }}
  {{- if and .Values.ingress.tls .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        {{- range .Values.ingress.hosts }}
        - {{ .host | quote }}
        {{- end }}
      {{- if .Values.ingress.tls.secretName }}
      secretName: {{ .Values.ingress.tls.secretName }}
      {{- end }}
  {{- end }}
  rules:
    {{- $fullName := include "whoami.fullname" . }}
    {{- $svcName := printf "%s-svc" $fullName }}
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $svcName }}
                port:
                  number: {{ .port }}
          {{- end }}
    {{- end }}
{{- end }}