apiVersion: v1
kind: Service
metadata:
  name: {{ include "whoami.fullname" . }}-svc
  labels:
    app: {{ include "whoami.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: web
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ include "whoami.name" . }}