apiVersion: v1
kind: Service
metadata:
  name: {{ include "whoami.fullname" . }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "whoami.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "whoami.selectorLabels" . | nindent 4 }}